name: wog_bible_section
description: Bible section for WOG App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Baloo Tammudu 2 ఫాంట్ కోసం
  google_fonts: ^6.2.1
  # మీ bible.xml ఫైల్ ని చదవడానికి
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # మీ XML ఫైల్ యాప్ కి లింక్ చేయడానికి
  assets:
    - assets/bible.xml
