name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main 

# 403 ఎర్రర్ రాకుండా GitHub బాట్ కి పర్మిషన్స్ ఇస్తున్నాము
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        # మీ రిపోజిటరీ పేరు ప్రకారం కరెక్ట్ బేస్ పాత్
        run: flutter build web --base-href "/wog_bible_section/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          
